### ISSUE TITLE
AGP 8.0 isn't supported: Stop using Transform API

### ISSUE THREAD

**Issue by bddckr** [RikkaApps/HiddenApiRefinePlugin#16]
As seen in https://github.com/RikkaApps/HiddenApiRefinePlugin/issues/14#issuecomment-1334663554:

> ```
> WARNING:API 'android.registerTransform' is obsolete.
> It will be removed in version 8.0 of the Android Gradle plugin.
> The Transform API is removed to improve build performance. Projects that use the
> Transform API force the Android Gradle plugin to use a less optimized flow for the
> build that can result in large regressions in build times. It’s also difficult to
> use the Transform API and combine it with other Gradle features; the replacement
> APIs aim to make it easier to extend the build without introducing performance or
> correctness issues.
> 
> There is no single replacement for the Transform API—there are new, targeted
> APIs for each use case. All the replacement APIs are in the
> `androidComponents {}` block.
> 
> The Transform API uses incremental APIs deprecated since Gradle 7.5. Please add
> `android.experimental.legacyTransform.forceNonIncremental=true` to
> `gradle.properties` to fix this issue. Note that this will run transforms
> non-incrementally and may have a build performance impact.
> For more information, see https://developer.android.com/studio/releases/gradle-plugin-api-updates#transform-api.
> To determine what is calling android.registerTransform, use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
> ```

**Comment by RikkaW** [comment]
Version 4.0.0 migrated to the new API.
