### ISSUE TITLE
Plugin version 4.0.0 no longer transforms unit and instrumentation test components

### ISSUE THREAD

**Issue by bddckr** [RikkaApps/HiddenApiRefinePlugin#18]
I believe all that's needed is to change this
https://github.com/RikkaApps/HiddenApiRefinePlugin/blob/b06bb6714f49aeccc11141265c630c8a00e4b210/gradle-plugin/src/main/java/dev/rikka/tools/refine/RefinePlugin.java#L23-L30

to also transform the `unitTest` and `androidTest` components of the `variant`.

**Comment by 1fexd** [comment]
Why is this necessary? Wouldn't this only be of any use if classes using the `*Hidden` stubs are in the test variant? This changes breaks any usage with Robolectric, #20

**Comment by mayurp95823-cyber** [comment]
https://github.com/RikkaApps/HiddenApiRefinePlugin/pull/19
